### ISSUE TITLE
Add support for govee smart buttons

### ISSUE THREAD

**Issue by Fefedu973** [constructorfleet/ultimate-govee#152]
**Is your feature request related to a problem? Please describe:**

Idk

**Describe the solution you'd like:**

A way to detect when a govee smart button is pressed

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Teagan42** [comment]
Unfortunately, there is no way anyone has found that can intercept the device state via the distributed gateway mechanism. This is the same situation for the Govee Motion Sensor (the Presence Sensor works with AWS IoT since it's WiFi enabled). These DW devices aren't event compatible with their new OpenAPI platform, which honestly I'm about as impressed with as I am the rest of Govee's APIs and Code (try decompiling the android application and you'll see just the quality developers they have working on their customer facing products).

The only way I found that even comes close to working is by creating an automatic tap-to-run automation, this creates an AWS IoT topic that is published to when it's run - but it wasn't the most reliable and you have to make the automation do something, not to mention Govee has upped their ACL game and now prevents subscription to device topics which pretty much negates this method now.
